services:
  - type: web
    name: tds-virtual-ta
    env: python
    plan: free
    buildCommand: "pip install --upgrade pip && pip install -r requirements.txt"
    startCommand: "uvicorn app:app --host 0.0.0.0 --port 10000"
    envVars:
      - key: API_KEY
        value: eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6IjIzZjEwMDA5MTRAZHMuc3R1ZHkuaWl0bS5hYy5pbiJ9.5guZd8fT-3r7haKzKadfsPiCjF-tKM6UF3oC-x9A9s0

